[package]
name = "cargot"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre         = "0.6"
crossterm          = "0.28"
ratatui            = "0.29"
cargo_metadata     = "0.19"
semver             = "1.0"
chrono = { version = "0.2.0", features = ["serde"] }
